# Permalinks
permalink:           pretty

# Setup
title:               Rob Gaston
tagline:             web|maps|culture|politics
url:                 http://blog.rgaston.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rob Gaston
  url:               https://rgaston.com
  email:             rob.m.gaston@gmail.com

# Custom vars
analytics_id:        UA-74433321-1
version:             2.0.0
github:
  repo:              https://github.com/rgaston/blog

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
